package com.gx.dao;


import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.gx.po.Company;




public interface CompanyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Mon Nov 06 14:52:45 CST 2017
	 */
//	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Mon Nov 06 14:52:45 CST 2017
	 */
	void insert(Company record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Mon Nov 06 14:52:45 CST 2017
	 */
//	int insertSelective(Result record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Mon Nov 06 14:52:45 CST 2017
	 */
	Company selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Mon Nov 06 14:52:45 CST 2017
	 */
//	int updateByPrimaryKeySelective(Result record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Mon Nov 06 14:52:45 CST 2017
	 */
//	int updateByPrimaryKey(Result record);
    
	List<Company> findBySQLforCompany(@Param(value="findBySQLforCompany") String findBySQL);
	
	 void updateByPrimaryKeyforCompany(Company record);
	  
	 Company findforCompany(Company record);
  
//	Date findBySQLforCLD(Date record);
	
}